name: CwComplete
author: mario_fischer
category: Forms
tags: [form, forms, autocomplete, autocompletion]
demo: http://www.chipwreck.de/blog/software/cwcomplete/demo/
docs: http://www.chipwreck.de/blog/software/cwcomplete/help/
current: 0.3

